name: Publish to GH Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0  # Ensures full commit history for submodules


      - name: Checkout destination
        if: github.ref == 'refs/heads/main'
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: built-site

      - name: Setup Hugo
        run: |
          HUGO_VERSION=$(curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
          echo "Using Hugo version $HUGO_VERSION"
          
          curl -L -o /tmp/hugo.tar.gz "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz"

          if ! tar -C ${RUNNER_TEMP} -zxvf /tmp/hugo.tar.gz hugo; then
            echo "Error: Failed to extract Hugo."
            exit 1
          fi

      - name: Build
        run: ${RUNNER_TEMP}/hugo --minify

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          cp -R public/* ${GITHUB_WORKSPACE}/built-site/
          cd ${GITHUB_WORKSPACE}/built-site
          
          git add .
          git config user.name 'jasmeetSSalh'
          git config user.email 'jasmeetsalh4@gmail.com'
          git commit -m 'Updated site' || echo "No changes to commit"
          git push
